#!/usr/bin/env python3

import sys
import os
import requests
import json
from pprint import pprint

args = sys.argv
server = os.environ.get("SERVER_ADDR")

if server:
    if len(args) > 1:
        if args[1] == "adicionar":
            if len(args) > 3:
                req = requests.post(url=server+"/Tarefa", data=json.dumps({"titulo": args[2], "content": args[3]}))
                print(req)
            else:
                print("Formato adicionar: adicionar titulo content")

        elif args[1] == "listar":
            req = requests.get(url=server+"/Tarefa")
            pprint (req.json())
        
        elif args[1] == "buscar":
            if len(args) > 2:
                req = requests.get(url=server+"/Tarefa/"+args[2])
                pprint (req.json())
            else:
                print("Formato buscar: buscar id")
        
        elif args[1] == "apagar":
            if len(args) > 2:
                req = requests.delete(url=server+"/Tarefa/"+args[2])
                pprint(req.json())
            else:
                print("Formato buscar: apagar id")

        elif args[1] == "atualizar":
            if len(args) > 3:
                new_content = ' '.join(args[3:])
                req = requests.put(url=server+"/Tarefa/"+args[2], data=json.dumps({"content": new_content}))
                pprint(req.json())
            else:
                print("Formato atualizar: atualizar id new_content")
        else:
            print("Comandos válidos: adicionar, listar, buscar, apagar e atualizar")
    else:
        print("Diga o comando que quer")

else:
    print("Rode criaVar.sh primeiro")
